## Create Admin
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Admin",
    "email": "admin@user.com",
    "password": "admin",
    "role": "ADMIN"
}

###

## GET Usrrs
GET http://localhost:3000/users
Authorization: Bearer {{token}}

###

# @name adminLogin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "admin@user.com",
    "password": "admin"
}

###

@token = {{ adminLogin.response.body.access_token }}

###